# action.yml
name: 'Download File Action'
description: 'GitHub Action to download files from certain URL.'
branding:
  icon: 'file'
  color: 'green'
inputs:
  url:  # id of input
    description: 'URL to download file from'
    required: true
  path:
    description: 'Path to store output file'
    required: false
    default: '${{ github.workspace }}'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.url }}
    - ${{ inputs.path }}
